name: C++ Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up MSBuild
      if: runner.os == 'Windows'
      uses: microsoft/setup-msbuild@v2

    - name: Compile C++ project
      if: runner.os == 'Windows'
      run: |
        dir gravi
        cl /EHsc source.cpp /Fe:gravi.exe

    - name: Run compiled program
      run: |
        .\gravi.exe

    - name: Check output file
      run: |
        if (Test-Path "output.csv") {
          Write-Host "Output generated successfully"
        } else {
          Write-Error "Output file not found"
        }
